Create classes
NickEmma/oop-school-library pull request #1
Opened 2022-09-26 22:19 UTC by NickEmma

In this milestone i implemented;

-  The Person class was created.
-  The student class was created and extended from the parent class.
-  The teacher class was created and extended from the parent class.

2022-09-26 22:56 UTC, Wes-Isaac requested changes
Hi @NickEmma, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Professional README 👀.
- Great PR description 👍.
- No linter error ✅.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-26 22:56 UTC, Wes-Isaac commented on person.rb
> +
- [ ] Great job so far on the requirement it says that we only need a Getter for` id`, here we have getter and setter, kindly fix that.

![image](https://user-images.githubusercontent.com/59416136/192394910-32b1de3c-2fac-4a98-9598-bfa15828328f.png)

2022-09-26 23:04 UTC, NickEmma commented on person.rb
> +
@Wes-Isaac i don't understand

2022-09-26 23:07 UTC, Wes-Isaac commented on person.rb
> +
`attr_accessor` defines both getter and setter attr_reader defines only getters so for the id we specifically need to say `attr_reader @id`

2022-09-26 23:20 UTC, NickEmma commented
Sir you know that attr_accessor is a method like a short circuit that
combines both attr_reader and attr_writer together

On Tue, Sep 27, 2022, 12:07 AM Isaac ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In person.rb
> <https://github.com/NickEmma/oop-school-library/pull/1#discussion_r980583713>
> :
>
> > +class Person
> +  attr_accessor :id, :name, :age, :parent_permission
> +
>
> attr_accessor defines both getter and setter attr_reader defines only
> getters so for the id we specifically need to say attr_reader @id
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NickEmma/oop-school-library/pull/1#discussion_r980583713>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQRCRRKIL7HA375OD5JP4RTWAIUDRANCNFSM6AAAAAAQWHASE4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-26 23:21 UTC, BenMukebo requested changes
Hi @NickEmma, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 23:21 UTC, BenMukebo commented on person.rb
> +  attr_accessor :id, :name, :age, :parent_permission
- [ ] As required by the previous reviewer, make sure you can only be able to retrieve the `id` so that means only the Getter must be defined. Your code might look like this:

```ruby
  attr_accessor :name, :age 
  attr_reader :id 
```

2022-09-26 23:21 UTC, BenMukebo commented on teacher.rb
> +  end
- [OPTIONAL] Let's list the `parent_permission ` to the construction and don't forget to add it to the super as weell👇🏻 

```ruby
  def initialize(age, specialization, name = "Unknown", parent_permission = true)
    super(age, name, parent_permission)
    @specialization = specialization
  end
```

2022-09-27 00:25 UTC, NickEmma commented on person.rb
> +  attr_accessor :id, :name, :age, :parent_permission
done

2022-09-27 00:34 UTC, mateo951 approved these changes
### Hi @NickEmma, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🐐 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 06:18 UTC, merged

2022-10-14 11:09 UTC, NickEmma commented on person.rb
> +
@Wes-Isaac Thank you for reviewing my project, I will make the necessary  corrections as suggested

2022-10-14 11:10 UTC, NickEmma commented on person.rb
> +  attr_accessor :id, :name, :age, :parent_permission
@BenMukebo Thank you for reviewing my project, I will make the necessary  corrections as suggested

2022-10-14 11:10 UTC, NickEmma commented
@mateo951 Thank you for reviewing and approving our code.